In [1]:
import numpy as np
import numpy.matlib
import matplotlib.pyplot as plt
from matplotlib import style;  style.use('ggplot')
from sklearn.datasets.samples_generator import make_blobs

In [3]:
import gnumpy as gnp

ImportError: No module named 'gnumpy'

In [11]:
X, x = make_blobs(n_samples=1, centers=1, n_features=2)
Y, y = make_blobs(n_samples=1, centers=1, n_features=2)
print (np.linalg.norm(X.T[:,0]-Y.T[:,0]))

15.7395500597


In [30]:
tmp = np.vstack((X.T, Y.T))
tmp

array([[-7.97269736],
       [ 5.62592181],
       [ 6.20452323],
       [-1.21073326]])

In [31]:
np.add(X.T, Y.T)

array([[-1.76817413],
       [ 4.41518855]])

In [13]:
Y

array([[ 6.20452323, -1.21073326]])