In [3]:
import numpy as np

In [235]:
def fuck_bsas(X, theta, q, order):
    [l, N] = X.shape
    n_clust = 1
    
    if (len(order) == 0):
        order = range(N)
        
    bel = np.zeros((1,N))    
    bel[0, order[0]] = n_clust
    repre = X[:, order[0]]
    repre = np.array([repre]).T
    
    for i in range(1, N):
        try:
            [m1, m2] = repre.shape
        except ValueError: 
            m1 = repre.shape
            m2 = 1
            
        tmp = np.dot(np.array([X[:, order[i]]]).T, np.ones((1,m2)))
        tmp = np.subtract(repre, tmp)
        tmp = np.sqrt(np.sum(np.square(tmp)))
               
        s1 = tmp.min()
        s2 = tmp.argmin()
        
        if ((s1 > theta) and (n_clust < q)):
            n_clust+=1
            bel[0, order[i]] = n_clust
            repre = np.concatenate((repre, np.array([X[:, order[i]]]).T), axis=1)
        else:
            bel[0, order[i]] = s2
            
            tmp = np.sum(np.equal(bel, s2))
            repre[:, s2] = ( (tmp - 1)*repre[:, s2] + X[:, order[i]] ) / tmp
    return bel, repre

In [248]:
X = np.array([[2, 5], [6, 4], [5, 3], [2, 2], [1, 4], [5, 4], [3, 3], [2, 3], 
              [2, 4], [8, 2], [9, 2], [10, 2], [11, 2], [10, 3], [9, 1]]).T;
print (X)

q = 15;
theta = 2.5;
order = np.array([7, 5, 10, 0, 4, 1, 2, 3, 6, 9, 8, 11, 12, 13, 14]);

[bel_2, repre_2]=fuck_bsas(X,theta,q,order)
print(bel_2)
print(repre_2)


[[ 2  6  5  2  1  5  3  2  2  8  9 10 11 10  9]
 [ 5  4  3  2  4  4  3  3  4  2  2  2  2  3  1]]
[[  4.   6.   7.   8.   5.   2.   9.   1.  11.  10.   3.  12.  13.  14.
   15.]]
[[ 2  5  9  2  1  6  5  2  3  8  2 10 11 10  9]
 [ 3  4  2  5  4  4  3  2  3  2  4  2  2  3  1]]


In [232]:
a = [[3], [3]]
b = [[4], [4]]

np.concatenate((a,b), axis=1)

array([[3, 4],
       [3, 4]])