In [64]:
import numpy as np
import numpy.matlib
import matplotlib.pyplot as plt
from scipy.spatial.distance import euclidean
from matplotlib import style;  style.use('ggplot')
from sklearn.datasets.samples_generator import make_blobs

In [54]:
X, x = make_blobs(n_samples=1, centers=1, n_features=2)
Y, y = make_blobs(n_samples=1, centers=1, n_features=2)
print (np.linalg.norm(X.T[:,0]-Y.T[:,0]))

8.36615095545


In [55]:
tmp = np.vstack((X.T, Y.T))
tmp

array([[-1.44203578],
       [ 5.07463294],
       [-7.53642837],
       [-0.65693409]])

In [56]:
np.add(X.T, Y.T)

array([[-8.97846415],
       [ 4.41769885]])

In [57]:
Y

array([[-7.53642837, -0.65693409]])

In [58]:
clusters = {}; m = 1
clusters[m-1] = X.T

In [62]:
from sklearn.metrics.pairwise import euclidean_distances
from scipy.spatial.distance import euclidean

In [63]:
euclidean(X.T[:,0], X.T[:,0])

0.0