In [1]:
import numpy as np
import numpy.matlib
import matplotlib.pyplot as plt
from scipy.spatial.distance import euclidean
from matplotlib import style;  style.use('ggplot')
from sklearn.datasets.samples_generator import make_blobs

In [2]:
X, x = make_blobs(n_samples=1, centers=1, n_features=2)
Y, y = make_blobs(n_samples=1, centers=1, n_features=2)
print (np.linalg.norm(X.T[:,0]-Y.T[:,0]))

17.0939750523


In [25]:
tmp = np.hstack((X.T, Y.T))
tmp

array([[ 7.140223  , -3.3759804 ],
       [-9.09665171,  4.37975171]])

In [5]:
np.add(X.T, Y.T)

array([[ 3.76424261],
       [-4.7169    ]])

In [6]:
Y

array([[-3.3759804 ,  4.37975171]])

In [7]:
clusters = {}; m = 1
clusters[m-1] = X.T

In [2]:
from sklearn.metrics.pairwise import euclidean_distances
from scipy.spatial.distance import euclidean

In [26]:
euclidean(X.T[:,0], X.T[:,0])

0.0

In [13]:
-np.inf

-inf

In [23]:
for column_i in range(tmp.shape[1]):                
    print (column_i)
    print (tmp[:,column_i])
    print ("gfhugfiuhgfhuolgdfuihl")

0
[ 7.140223   -9.09665171]
gfhugfiuhgfhuolgdfuihl
1
[-3.3759804   4.37975171]
gfhugfiuhgfhuolgdfuihl


In [4]:
from tqdm import tqdm_notebook
import time

In [ ]:
for i in tqdm_notebook(range(1615)):
    for j in tqdm_notebook(range(100), desc=('%s loop'%(i))):
        time.sleep(0.01)

In [4]:
np.min([1,2,3,4])

array([ 1,  3,  4, 12])